name: Docker GHA

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      r_version:
        description: 'R version to use'
        required: true
        type: choice
        default: "4.1"
        options:
          - 4.1
          - 4.2
          - 4.3
          - 4.4
          - devel

# set up the environment, either input or default
env:
  R_VERSION: ${{ github.event.inputs.r_version || '4.1' }}

# there are 3 jobs to build different images
jobs:
  # ----------------------------------------------------------------------
  # depends image has all the dependencies installed
  # ----------------------------------------------------------------------
  depends:
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: depends
      build-context: docker/depends
      dockerfile-path: docker/depends/Dockerfile
      R-version: ${{ env.R_VERSION }}
      platforms: "linux/amd64"
    secrets: inherit

  # ----------------------------------------------------------------------
  # base image has PEcAn compiled and installed, and depends on depends
  # ----------------------------------------------------------------------
  base:
    needs: depends
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: base
      build-context: .
      dockerfile-path: docker/base/Dockerfile
      R-version: ${{ env.R_VERSION }}
      from-image: depends
      platforms: "linux/amd64"
    secrets: inherit

# ----------------------------------------------------------------------
# models image has some python installed to run models, depends on base
# ----------------------------------------------------------------------
  models:
    needs: base
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: models
      build-context: docker/models
      dockerfile-path: docker/models/Dockerfile
      R-version: ${{ env.R_VERSION }}
      from-image: depends # TODO is this correct? Dockerfile hardcodes FROM pecan/base
    secrets: inherit

# ----------------------------------------------------------------------
# Next are images that have models installed
# ----------------------------------------------------------------------
  modelsbinary:
    needs: models    
    strategy:
      fail-fast: false
      matrix:
        name:
          - basgra
          - biocro
          # - ed2_2.2.0
          - ed2_git
          - maespa
          - sipnet
        include:
          - name: basgra
            CONTEXT: models/basgra
            DOCKERFILE: models/basgra/Dockerfile
            PLATFORM: "linux/amd64"
            MODEL: basgra
            VERSION: BASGRA_N_v1
          - name: biocro
            CONTEXT: models/biocro
            DOCKERFILE: models/biocro/Dockerfile
            PLATFORM: "linux/amd64"
            MODEL: biocro
            VERSION: "0.95"
          # - name: ed2_2.2.0
          #   CONTEXT: models/ed
          #   DOCKERFILE: models/ed/Dockerfile
          #   PLATFORM: "linux/amd64"
          #   MODEL: ed2
          #   VERSION: "2.2.0"
          - name: ed2_git
            CONTEXT: models/ed
            DOCKERFILE: models/ed/Dockerfile
            PLATFORM: "linux/amd64"
            MODEL: ed2
            VERSION: "git"
          - name: maespa
            CONTEXT: models/maespa
            DOCKERFILE: models/maespa/Dockerfile
            PLATFORM: "linux/amd64"
            MODEL: maespa
            VERSION: "git"
          - name: sipnet
            CONTEXT: models/sipnet
            DOCKERFILE: models/sipnet/Dockerfile
            PLATFORM: "linux/amd64"
            MODEL: sipnet
            VERSION: "git"
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: model-${{ matrix.MODEL }}-${{ matrix.VERSION }}
      build-context: ${{ matrix.CONTEXT }}
      dockerfile-path: ${{ matrix.DOCKERFILE }}
      R-version: ${{ env.R_VERSION }}
      # no `from-image:` needed here -- it's hardcoded as `FROM pecan/models` in the Dockerfiles
      model-version: ${{ matrix.VERSION }}
      platforms: ${{ matrix.PLATFORM }}
    secrets: inherit

  # ----------------------------------------------------------------------
  # Next are images that depend on base image
  # ----------------------------------------------------------------------
  baseplus:
    needs: base
    strategy:
      fail-fast: false
      matrix:
        name:
          - docs
          - executor
          - api
        include:
          - name: docs
            CONTEXT: .
            DOCKERFILE: docker/docs/Dockerfile
            PLATFORM: "linux/amd64"
            IMAGE: docs
          - name: executor
            CONTEXT: docker/executor
            DOCKERFILE: docker/executor/Dockerfile
            PLATFORM: "linux/amd64"
            IMAGE: executor
          - name: api
            CONTEXT: apps/api
            DOCKERFILE: apps/api/Dockerfile
            PLATFORM: "linux/amd64"
            IMAGE: api
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: ${{ matrix.IMAGE }}
      build-context: ${{ matrix.CONTEXT }}
      dockerfile-path: ${{ matrix.DOCKERFILE }}
      R-version: ${{ env.R_VERSION }}
      platforms: ${{ matrix.PLATFORM }}
    secrets: inherit

  # ----------------------------------------------------------------------
  # Next are images that do not depend on either depends or base image
  # ----------------------------------------------------------------------
  extras:
    strategy:
      fail-fast: false
      matrix:
        name:
          - web
          - dbsync
          - data
          - monitor
          - rstudio-nginx
        include:
          - name: web
            CONTEXT: .
            DOCKERFILE: docker/web/Dockerfile
            PLATFORM: "linux/amd64,linux/arm64"
            IMAGE: web
          - name: dbsync
            CONTEXT: .
            DOCKERFILE: shiny/dbsync/Dockerfile
            PLATFORM: "linux/amd64"
            IMAGE: shiny-dbsync
          - name: data
            CONTEXT: docker/data
            DOCKERFILE: docker/data/Dockerfile
            PLATFORM: "linux/amd64,linux/arm64"
            IMAGE: data
          - name: monitor
            CONTEXT: docker/monitor
            DOCKERFILE: docker/monitor/Dockerfile
            PLATFORM: "linux/amd64,linux/arm64"
            IMAGE: monitor
          - name: rstudio-nginx
            CONTEXT: docker/rstudio-nginx
            DOCKERFILE: docker/rstudio-nginx/Dockerfile
            PLATFORM: "linux/amd64,linux/arm64"
            IMAGE: rstudio-nginx
    uses: ./.github/workflows/docker-build-image.yml
    with:
      image-name: ${{ matrix.IMAGE }}
      build-context: ${{ matrix.CONTEXT }}
      dockerfile-path: ${{ matrix.DOCKERFILE }}
      platforms: ${{ matrix.PLATFORM }}
      R-version: ${{ env.R_VERSION }}
