on:
  issue_comment:
    types: [created]
name: Commands
jobs:
  style:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: macOS-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: list changed files
        run: echo '${{ steps.file_changes.outputs.files_modified }}'
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("styler", "devtools"), repos = "cloud.r-project.org")'
          Rscript -e 'devtools::install_version("roxygen2", version = "7.0.2", repos = "cloud.r-project.org")'
      - name: string operations
        shell: bash
        run: |
          for i in ${{ join(steps.file_changes.outputs.files_modified, " ") }}; do;
            if [[ "$i" == *.R\" || "$i" == *.Rmd\" ]];
              then Rscript -e "styler::style_file("$i")";
            fi;
          done
      - name: commit
        run: |
          git add \*.R
          git add \*.Rmd
          if [ "$(git diff --name-only --cached)" != "" ]; then  git commit -m 'automated syle update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}


  check:
    if: (startsWith(github.event.comment.body, '/style') || startsWith(github.event.comment.body, '/document'))
    runs-on: ubuntu-latest
    container: pecan/depends:develop
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: update dependency lists
        run: Rscript scripts/generate_dependencies.R
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name : make
        shell: bash
        run: |
          echo ${{ join(steps.file_changes.outputs.files_modified, "\n") }} \
          | cut -d / -f 1-2 \
          | sort \
          | uniq \
          | grep -e base -e models -e modules \
          | xargs -n1 -I{} make .doc/{}
      - name: commit
        run: |
          git config --global user.email "pecan_bot@example.com"
          git config --global user.name "PEcAn stylebot"
          git add \*.Rd
          if [ "$(git diff --name-only --cached)" != "" ]; then  git commit -m 'automated documentation update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
